config/routes.rb
Rails.application.routes.draw do

  root            'static_pages#home' 

  get 'help'      => 'static_pages#help' 
  get 'about'     => 'static_pages#about' 
  get 'contact'   => 'static_pages#contact' 
  get 'signup'    => 'users#new' 
  get 'login'     => 'sessions#new'
  post 'login'    => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  
  resources :users
  resources :account_activations,  only: [:edit]
  resources :password_resets,      only: [:new, :create, :edit, :update]
  resources :herbs
  resources :foundational_actions
  resources :clinical_actions
  resources :affinities

end

app/controllers/clinical_actions_controller.rb
class ClinicalActionsController < PropertiesController
  before_action :set_property_type, only: [ :create, :update, :destroy ]

  def index
    @properties = ClinicalAction.paginate(page: params[:page])
  end

  def new
    @property = ClinicalAction.new
  end
  
  def create
    @property = ClinicalAction.new(action_params)
    super
  end 

  private

    def action_params
      params.require(:clinical_action).permit(:name, :description)
    end  

    def set_property_type
      @property_type = "clinical action"
    end
end

app/helpers/clinical_actions_helper.rb
module ClinicalActionsHelper
end

app/views/clinical_actions/_clinical_actions.html.erb
<%= will_paginate @properties %>

<dl class="actions">
  <% @properties.each do |property| %>
  <dt><%= link_to property.name, clinical_action_path(property) %></dt>
  <dd><%= property.description %>
    <% if editor? %>
      | <%= link_to "edit", edit_clinical_action_path(property) %> 
      | <%= link_to "delete", clinical_action_path(property), method: :delete,
                              data: { confirm: "You sure?" } %>
    <% end %>
</dd>
<% end %>
</dl>

 <%= will_paginate @properties %>

app/views/clinical_actions/index.html.erb
<% provide(:title, 'Clinical Actions') %>
<h1>Clinical Actions</h1>

<ul class="nav nav-tabs">
  <li role="presentation" class="active">
    <%= link_to 'Foundational Actions', foundational_actions_path %>
  </li>
  <li role="presentation">
    <%= link_to 'Clinical Actions', clinical_actions_path %>
  </li>
  <li role="presentation">
    <%= link_to 'Organ Affinities', affinities_path %>
  </li>
</ul>

<%#= render 'properties/properties' %>
<%= render 'clinical_actions' %>

app/views/clinical_actions/new.html.erb
<% provide :title, "New Clinical Action" %>
<h1>New Clinical Action</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'properties/form' %>
  </div>
</div>