config/routes.rb
Rails.application.routes.draw do

  root            'static_pages#home' 

  get 'help'      => 'static_pages#help' 
  get 'about'     => 'static_pages#about' 
  get 'contact'   => 'static_pages#contact' 
  get 'signup'    => 'users#new' 
  get 'login'     => 'sessions#new'
  post 'login'    => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  
  resources :users
  resources :account_activations,  only: [:edit]
  resources :password_resets,      only: [:new, :create, :edit, :update]
  resources :herbs
  resources :foundational_actions
  resources :clinical_actions
  resources :affinities

end

app/controllers/foundational_actions_controller.rb
class FoundationalActionsController < PropertiesController

  def index
    @properties = FoundationalAction.paginate(page: params[:page])
  end

  def new
    @property = FoundationalAction.new
  end
  
  def create
    @property = FoundationalAction.new(action_params)
    super
  end 

  private

    def action_params
      params.require(:foundational_action).permit(:name, :description)
    end  

    def set_property_type
      @property_type = "foundational action"
    end
end

app/views/foundational_actions/_foundational_actions.html.erb
<%= will_paginate @properties %>

<dl class="actions">
  <% @properties.each do |property| %>
  <dt><%= link_to property.name, foundational_action_path(property) %></dt>
  <dd><%= property.description %>
    <% if editor? %>
      | <%= link_to "edit", edit_foundational_action_path(property) %> 
      | <%= link_to "delete", foundational_action_path(property), method: :delete,
                              data: { confirm: "You sure?" } %>
    <% end %>
</dd>
<% end %>
</dl>

 <%= will_paginate @properties %>

app/views/foundational_actions/_property.html.erb
<dt><%= link_to property.name, property_path(property) %></dt>
<dd><%= property.description %>
  <% if editor? %>
    | <%= link_to "edit", edit_property_path(property) %> 
    | <%= link_to "delete", property_path(property), method: :delete,
                                  data: { confirm: "You sure?" } %>
  <% end %>
</dd>

app/views/foundational_actions/index.html.erb
<% provide(:title, 'Foundational Actions') %>
<h1>Foundational Actions</h1>

<ul class="nav nav-tabs">
  <li role="presentation" class="active">
    <%= link_to 'Foundational Actions', foundational_actions_path %>
  </li>
  <li role="presentation">
    <%= link_to 'Clinical Actions', clinical_actions_path %>
  </li>
  <li role="presentation">
    <%= link_to 'Organ Affinities', affinities_path %>
  </li>
</ul>

<%#= render 'properties/properties' %>
<%= render 'foundational_actions' %>

app/views/foundational_actions/new.html.erb
<% provide :title, "New Foundational Action" %>
<h1>New Foundational Action</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'properties/form' %>
  </div>
</div>