config/routes.rb
Rails.application.routes.draw do

  root            'static_pages#home' 

  get 'help'      => 'static_pages#help' 
  get 'about'     => 'static_pages#about' 
  get 'contact'   => 'static_pages#contact' 
  get 'signup'    => 'users#new' 
  get 'login'     => 'sessions#new'
  post 'login'    => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  
  resources :users
  resources :account_activations,  only: [:edit]
  resources :password_resets,      only: [:new, :create, :edit, :update]
  resources :herbs
  resources :foundational_actions
  resources :clinical_actions
  resources :affinities

end

app/models/affinity.rb
class Affinity < Property
  def display_type
    "Organ/tissue affinity"
  end
end

app/controllers/affinities_controller.rb
class AffinitiesController < PropertiesController

  def index
    @properties = Affinity.paginate(page: params[:page])
  end

  def new
    @property = Affinity.new
  end
  
  def create
    @property = Affinity.new(action_params)
    super
  end 

  private

    def action_params
      params.require(:affinity).permit(:name, :description)
    end  

    def set_property_type
      @property_type = "organ/tissue affinity"
    end
end

app/helpers/affinities_helper.rb
module AffinitiesHelper
end

app/views/affinities/_affinities.html.erb
<%= will_paginate @properties %>

<dl class="actions">
  <% @properties.each do |property| %>
  <dt><%= link_to property.name, affinity_path(property) %></dt>
  <dd><%= property.description %>
    <% if editor? %>
      | <%= link_to "edit", edit_affinity_path(property) %> 
      | <%= link_to "delete", affinity_path(property), method: :delete,
                              data: { confirm: "You sure?" } %>
    <% end %>
</dd>
<% end %>
</dl>

 <%= will_paginate @properties %>

app/views/affinities/index.html.erb
<% provide(:title, 'Organ Affinities') %>
<h1>Organ/Tissue Affinities</h1>

<ul class="nav nav-tabs">
  <li role="presentation" class="active">
    <%= link_to 'Foundational Actions', foundational_actions_path %>
  </li>
  <li role="presentation">
    <%= link_to 'Clinical Actions', clinical_actions_path %>
  </li>
  <li role="presentation">
    <%= link_to 'Organ Affinities', affinities_path %>
  </li>
</ul>

<%#= render 'properties/properties' %>
<%= render 'affinities' %>

app/views/affinities/new.html.erb
<% provide :title, "New Affinity" %>
<h1>New Affinity</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'properties/form' %>
  </div>
</div>